feat: add automated deploy

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,15 +1,32 @@
 stages:
   - lint
+  - build
   - test
   - deploy
 
 variables:
   PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
   PYTHONPATH: "$CI_PROJECT_DIR"
+  FF_DISABLE_PROFILE_LOADING: "true"
 
 cache:
   paths:
     - .cache/pip
+
+build:
+  stage: build
+  image: docker:24.0.5
+  services:
+    - docker:24.0.5-dind
+  script:
+    - export IMAGE_TAG=$(echo "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" | tr '[:upper:]' '[:lower:]')
+    # Use built-in CI_JOB_TOKEN (automatic, no variables needed)
+    - echo "$CI_PROJECT_DIR" | docker login -u "$CI_REGISTER_USER" --password-stdin "$CI_REGISTRY"
+    - docker build -f Dockerfile.prod -t "IMAGE_TAG"
+    - docker push "$IMAGE_TAG"
+    - docker logout "$CI_REGESTRY"
+
+  only: ["main"]
 
 lint:
   stage: lint
@@ -39,35 +56,60 @@ test:
 
 deploy:
   stage: deploy
-  image: alpine:latest
-  before_script:
-    - apk update && apk add openssh-client
-    - eval $(ssh-agent -s)
-    - chmod 400 "$SSH_PRIVATE_KEY"
-    - ssh-add "$SSH_PRIVATE_KEY"
-    - mkdir -p ~/.ssh
-    - chmod 700 ~/.ssh
-    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
+  tags:
+    - ec2-runner-robot
   script:
+    - export IMAGE_TAG=$(echo "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" | tr '[:upper:]' '[:lower:]')
+    # Login to registry (using CI_JOB_TOKEN is safer, but GI_REGISTRY_PASSWORD also works)
+    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTER_USER" --password-stdin "$CI_REGISTRY"
+    - docker pull "$IMAGE_TAG"
+    - docker logout "$CI_REGISTRY"
+    - mkdir -p /home/gitlab-runner/app
+    - cp "$CI_PROJECT_DIR/docker-compose.prod.yml" /home/gitlab-runner/app/
+    - cp "$CI_PROJECT_DIR/nginx.conf" /home/gitlab-runner/app/
+    - cd /home/gitlab-runner/app
+    # --- GET SECRETS FROM AWS SSM ---
+    - DB_PASS=$(aws ssm get-parameter --name "/prod/db_password" --with-decryption --region eu-central-1 | jq -r '.Parameter.Value')
+    - APP_SECRET=$(aws ssm get-parameter --name "/prod/secret_key") --with-decryption --region eu-central-1 | jq -r '.Parameter.Value')
+    - AWS_ACCESS_KEY=$(aws ssm get-parameter --name "/prod/aws_access_key_id" --with-decryption --region eu-central-1 | jq -r '.Parameter.Value')
+    - AWS_SECRET_KEY=$(aws ssm get-parameter --name "/prod/aws_secret_access_key" --with-decryption --region eu-central-1 | jq -r '.Parameter.Value')
+    # --- VALIDATE ALL SECRETS ---
     - |
-      ssh $EC2_USER@$EC2_HOST \
-        "DATABASE_URL='$PRODUCTION_DATABASE_URL' SECRET_KEY='$PRODUCTION_SECRET_KEY' bash -s" << 'ENDSSH'
-        set -e
-        if [ ! -d ~/robot-payment ]; then
-          git clone https://gitlab.com/alexvlasov182/robot-payment.git ~/robot-payment
-        fi
-        cd ~/robot-payment
-        git fetch --all
-        git reset --hard origin/main
-        echo "DATABASE_URL=$DATABASE_URL" > .env
-        echo "SECRET_KEY=$SECRET_KEY" >> .env
-        echo "APP_ENV=production" >> .env
-        echo "DEBUG=false" >> .env
-        echo "ALGORITHM=HS256" >> .env
-        echo "ACCESS_TOKEN_EXPIRE_MINUTES=30" >> .env
-        echo "REFRESH_TOKEN_EXPIRE_DAYS=7" >> .env
-        sudo docker compose -f docker-compose.prod.yml up -d --build
-        sudo docker exec robot-api alembic upgrade head
-      ENDSSH
+      if [ -z "$DB_PASS" ]; then
+        echo "ERROR: APP_SECRET is empty"
+        exit 1
+      fi
+    - |
+      if [ -z "$APP_SECRET" ]; then
+        echo "ERROR: APP_SECRET is empty"
+        exit 1
+      fi
+    - |
+      if [ -z "$AWS_ACCESS_KEY" ]; then
+        echo "ERROR: AWS_ACCESS_KEY is empty"
+        exit 1
+      fi
+    - |
+      if [ -z "$AWS_SECRET_KEY"]; then
+        echo "ERROR: AWS_SECRET_KEY is empty"
+      fi
+    # - |
+    #   if [ -z "$S3_BUCKET" ]; then
+    #     echo "ERROR: S3_BUCKET is empty"
+    #     exit 1
+    #   fi
+    # --- CREATE .env FILE ---
+    - echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY" >> .env
+    - echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY"
+    # - echo "S3_BUCKET_NAME=$S3_BUCKET" >> .env
+    # --- START CONTAINERS ---
+    - IMAGE_TAG="$IMAGE_TAG" docker compose -f docker-compose.prod.yml up -d --remove-orphans
+    - docker image prune -f
+    # --- HEALTH CHECK ---
+    - echo "Waiting for API to be ready..."
+    - for i in $(seq 1 30); do curl -f http://localhost/health && break || sleep 2; done
+
+    - echo "Depolyment successful!"
+    - docker ps
   only:
     - main
